BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
USE Flights2017
GO
DROP TABLE IF EXISTS [Airlines]
GO
CREATE TABLE [dbo].[Airlines]
	(
	[AirlineID] [nvarchar](100) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Alias] [nvarchar](100) NULL,
	[IATA] [nvarchar](10) NULL,
	[ICAO] [nvarchar](10) NULL,
	[Callsign] [nvarchar](100) NULL,
	[Country] [nvarchar](100) NULL,
	[Active] [nvarchar](10) NULL
	)  ON SECONDARY
GO
ALTER TABLE [dbo].[Airlines] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
